name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hardsource/fast-ci:${{ github.event.number == 0 && 'latest' || format('PR-{0}', github.event.number) }}

      - name: Disparar deployment em dev
        uses: benc-uk/workflow-dispatch@v1
        env:
          IMAGE_TAG: ${{ github.event.number == 0 && 'latest' || format('PR-{0}', github.event.number) }}
        with:
          workflow: cd.yml
          inputs: '{ "envronment": "dev", "imageTag": "${{ env.IMAGE_TAG }}" }'
          token: "${{ secrets.TOKEN_GITHUB }}"
